version: "3"
services:
    nodejs:
        build: ./Steelcraft-server/
        container_name: server
        ports:
            - "3000:3000"
        networks:
            - docker-network

    nginx:
        build: ./Steelcraft-client/
        container_name: nginx-server
        volumes:
            - ./Steelcraft-client/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        networks:
            - docker-network

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
        depends_on:
            - nginx
networks:
    docker-network:
        driver: bridge